<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[App Login Succseefull]]>
    </line>
  </reporter-output>
  <suite started-at="2024-02-29T12:08:58 IST" name="Suite" finished-at="2024-02-29T12:09:14 IST" duration-ms="15798">
    <groups>
    </groups>
    <test started-at="2024-02-29T12:08:58 IST" name="Test" finished-at="2024-02-29T12:09:14 IST" duration-ms="15798">
      <class name="myTestNG.TestScreenShort">
        <test-method is-config="true" signature="configureReport()[pri:0, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:08:58 IST" name="configureReport" finished-at="2024-02-29T12:08:59 IST" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureReport -->
        <test-method is-config="true" signature="lunchBrowser()[pri:0, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:08:59 IST" name="lunchBrowser" finished-at="2024-02-29T12:09:10 IST" duration-ms="11468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method signature="login()[pri:1, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:09:10 IST" name="login" finished-at="2024-02-29T12:09:12 IST" duration-ms="2041" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://www.automationpractice.pl/index.php?controller=my-account] but found [http://www.automationpractice.pl/index.php?controller=authentication]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://www.automationpractice.pl/index.php?controller=my-account] but found [http://www.automationpractice.pl/index.php?controller=authentication]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at myTestNG.TestScreenShort.login(TestScreenShort.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[App Login Succseefull]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:09:13 IST" name="closeBrowser" finished-at="2024-02-29T12:09:13 IST" duration-ms="537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:09:13 IST" name="getTestResult" finished-at="2024-02-29T12:09:13 IST" duration-ms="36" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=TestScreenShort.login()[pri:1, instance:myTestNG.TestScreenShort@18f8cd79] output=App Login Succseefull]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:myTestNG.TestScreenShort@18f8cd79]" started-at="2024-02-29T12:09:13 IST" name="tearDown" finished-at="2024-02-29T12:09:14 IST" duration-ms="643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- myTestNG.TestScreenShort -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
